base_config: ../../configs/QECR默认配置.yaml

model_name: qecr_v01_query_distribution

model:
  query_depth:
    enabled: true
    cross_layer_refine: false
    num_points: 1

trainer:
  save_path: outputs/QECR消融实验/V01_查询级局部分布/

